spring:
  datasource:
    username: postgres
    password: fannysammy53

application:
  security:
    jwt:
      secret-key: O44FVQ6MlXUD5oxaPn7D77DfeSAISRw5G0om05SDvMqst6HZvLZ2obVA2XlCFC41
      expiration: 8600000 # one day
#      expiration: 60000 # one minute
      refresh-token:
        expiration: 604800000 #7 days


sendinblue:
  api:
    key: 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
  mail:
    url: https://api.sendinblue.com/v3/smtp/email


